[package]
name = "html-purifier"
version = "0.1.0"
authors = ["mehmetcansahin <sahinmcan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.11.0"